### ISSUE TITLE
W10 Won't connect to server running on same computer

### ISSUE THREAD

**Issue by jackson1442** [iTXTech/Genisys#1305]
#### Issue description

This may just be me being a n00b, but I'm trying to run the server and W10 edition on the same computer and the game can show the server in the options for connecting, but can't connect.
#### OS and versions

* Genisys: 1.2dev-518
* PHP: idk
* OS: Win10

**Comment by PeratX** [comment]
Because win10 edition also listening on port 19132

**Comment by dktapps** [comment]
It's an MC Win10 bug. Never used to happen on 0.14.3. Granted, it's not our fault, because you can open to a different port and add the IP/port manually and it _still_ can't see it, but this is a new thing. It's actually really annoying (especially for a Win10 dev like myself!), but nothing we can do about it. I have heard tell that if you portforward and then input the external IP/port manually it will work, but don't hold me to that, I haven't been able to try it.
