### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by Crypthu** [iTXTech/Genisys#1353]
Please fix fps drop!

**Comment by gaoyichuan** [comment]
Totally **client** side issue!

**Comment by Crypthu** [comment]
? Client? .-.

**Comment by Muqsit** [comment]
@gaoyichuan I thought it was client sided too but this issue is due to the SIGN tile. On my server, the shop has got around 75 wall signs and the fps is around 10-15. The fps drops only in the chunk, not outside it.I tried removing all wall signs (68:0) from the spawn and the fps drop just vanished. I think signs aren't coded correctly.

**Comment by Crypthu** [comment]
M fix :) only plugin bug.. :D delete and good fps :3 no problem

**Comment by gaoyichuan** [comment]
@Muqsit You can try to place the same amount of signs in singleplayer. You will get the same lag

**Comment by Muqsit** [comment]
@gaoyichuan you're right 0.0
