### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1482]
Warning: Division by zero in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/utils/VectorIterator.php on line 122

Warning: Division by zero in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/utils/VectorIterator.php on line 127

Warning: Division by zero in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/utils/VectorIterator.php on line 129

Warning: Division by zero in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/utils/VectorIterator.php on line 174

Version
Genisys git-b6b3aeb

After that , server freeze!!

**Comment by ZedCee** [comment]
Sorry but without following the template there is not enough information to help with this issue.

**Comment by TDMidkwhatisxd** [comment]
Im moving from genisys !!! -_-  !!

**Comment by ZedCee** [comment]
@TDMidkwhatisxd The issue is not knowing what your OS, PHP, Client, or plugins are and how the issue occurred.  The issue cant begin to be solved without those details.  
A friendly per-formatted template is provided that shows the required information to even begin to find, test and solve an issue.  Which regardless of the repo, you will eventually be asked all of those things.  
Until the adequate template is provided, the issue stays closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.

**Comment by ZedCee** [comment]
@TDMidkwhatisxd I have kindly included the template back into your issue ticket.  If you would like to receive support please fill out the remaining information.
