### ISSUE TITLE
Doors don't drop when removing the block underneath

### ISSUE THREAD

**Issue by yar2001** [iTXTech/Genisys#1491]
#### Issue description
打破门底部的方块，门不会有掉落物产生
If you break the block under the door, the door will not have a drop.

#### Steps to reproduce the issue
使用iTX最新核心，一个玩家怒气冲冲的跟我说他的铁门被服务器吃掉了，因为他打破了铁门底下的方块。我自己使用生存模式试了一下，包括橡木门和铁门均会如此。然而在原版中，打破门下方方块门应当有掉落物的。
1.Put a door
2.Break the block under the door
3.The door disapper but don't have a drop.
#### OS and versions
* Genisys: git-ab35ad3
* PHP:7.0.4
* Server OS:Windows server 2012
* Game version: Windows 10 Edition Beta 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files
iTX后台没有报错
ITX did not report errors

@ZedCee I'm sorry, I'm using the template now.

**Comment by CubeFromSpace** [comment]
Check src/Pocketmine/block/door.php. I can't find what is wrong otherwise

**Comment by ZedCee** [comment]
@yar2001 Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.  
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.  
Could you please provide the required information and we can begin to further investigate this issue.
Because Genisys is a bleeding release, it is always good to know the exact version you are using.

Understanding that English is not your native language it is perfectly acceptable to convert the template to Chinese, as both languages are accepted by Genisys

@PeratX maybe you could assist.  Thanks

**Comment by dktapps** [comment]
I'll handle this shortly.

**Comment by CubeFromSpace** [comment]
This probably is because Genysis "thinks" that the door "needs" to be broken directly.

**Comment by ZedCee** [comment]
@yar2001 Thank you a great deal for filling in the template. It helps greatly with bug fixing
