### ISSUE TITLE
Anvil and MCRegion

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1503]
#### Issue description

Do not use Anvil for Pocketmine! It will cause more server lag
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
How so?  I've been using it since I wanted to use MCEdit and have noticed no difference in speed between using the two (I have some maps that I can't convert yet).   
I can understand your concern, but it's just a switch so you can easily change it back to MCRegion if you like, but it looks like Anvil is becoming an MC standard.  There are also a great deal of improvements in the works, that in essence fix other errors that cause some of the lag.

**Comment by ZedCee** [comment]
http://minecraft.gamepedia.com/Anvil_file_format
@TheAppleGamer Anvil is an upgrade to mcregion; the formats are virtually the same, with minor changes in handling.  Hopefully this explains the move more.
Many of the special block types removed in Anvil are already removed from the present mcregion format.  Hopefully this helps explain the changes.
