### ISSUE TITLE
Chunks

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#1550]
#### Issue description

Generator branch have problem. With new populator,chunks not loaded and get clash server. Please delete amount of population in biomes for fix

#### Steps to reproduce the issue

Enter world and go

#### OS and versions

* Genisys:  Genisys_unsupported-f587830_2016-07-28_03-28-56
* PHP: 7.0.6
* Server OS: Windows 10 Pro 
* Game version: 0.15.3

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by caspervanneck** [comment]
What @Nycuro do you use genisys

**Comment by NycuRO** [comment]
@caspervanneck yes for test newest

**Comment by NycuRO** [comment]
@dktapps @PeratX

**Comment by ZedCee** [comment]
As it says in the version, you are using a version of Genisys from an unsupported branch.  Since it is still heavily in testing and in a beta state, it is a **use at your own risk copy of the server**.  There will be frequent breakages in their incomplete state and issue tickets are for issues relating to the master branch.  Windows 10 is also not supported currently and has a high number of breakages in any branch other than the one for Windows 10.

Further more, the unnecessary pinging of other users is considered spam.  Members of the iTX Technology organization can easily see all changes, issue tickets, and comments without the need to ping them.  You have left a trail of unneeded comments with only pings following your initial posts, which can also easily be edited to add direct mentions (pings) after the fact.  Also note any comments in reply are automatically watched in the dashboard without the need for direct mentions.

I apologize, but this issue ticket will be closed.  We appreciate the proper use of the issue template, but the spam only slows development and is in bad taste and form.

**Comment by caspervanneck** [comment]
@zedcee its not spam i tink

**Comment by caspervanneck** [comment]
Nycuro is good dev
