### ISSUE TITLE
Invincible spawner mobs

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1562]
#### Issue description
When mobs spawn in a spawner, they become invincible after a period of time.
#### Steps to reproduce the issue

Place a monster spawner, put in a IG or blaze (may be a issue with other mobs, have not tested) and have them spawn and wait, with will not take damage.
#### OS and versions

* Genisys: The one of off gitlab
* PHP: 7
* Server OS: mAc
* Game version: 0.15.4

**Comment by ZedCee** [comment]
Please properly clarify the version number in the template or the issue will be closed.
I also recommend you test it again with other mobs and any plugins temporarily disabled (rename the plugin directory).

**Comment by ZedCee** [comment]
I cannot reproduce this issue both mobs die fine for me.  Nor am I sure how you have working IG spawn eggs, as NBT tags are not implemented in the /give command.

**Comment by SuperDude36** [comment]
Iron golem spawn eggs are 383:20

**Comment by ZedCee** [comment]
IronGolem eggs do not work and I cannot reproduce the error with blazes.

I still do not know which version you are using and so this issue will remain closed until you update your issue ticket with the proper information.  Otherwise no further bug testing can take place.

**Comment by SuperDude36** [comment]
They do for me /give [name] 383:20 place em down and bingo!

**Comment by ZedCee** [comment]
Still ultimately you have not provided a version number.  
So if my inability to produce Iron Golems from spawn eggs is a new error, I cannot trace back to when it worked.  Without all the required information, we can't properly replicate the issue or know if you are actually using the latest version.

I have since tested more mobs from spawners and cannot reproduce the invincibility issue.

**Comment by SuperDude36** [comment]
Version: Genisys-968f026
