### ISSUE TITLE
Command about mp and makeplugin has gone in last version. 

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1564]
Look up the handLine.
I can't pack up my plugin.
That's so pity, I have to pack up in old version.
ERRO COMMAND LOST

**Comment by ibookcc** [comment]
Please give me a ansewer.

**Comment by Yoyu666** [comment]
stop spam,just wait!

**Comment by Muqsit** [comment]
For answer, click the 'Commits' button.

**Comment by ibookcc** [comment]
@Yoyu666 What's happen?

**Comment by Muqsit** [comment]
https://github.com/iTXTech/Genisys/pull/1523

**Comment by dktapps** [comment]
These commands have been removed from the server core. Please use Genisys-DevTools instead.
https://github.com/iTXTech/Genisys-DevTools

**Comment by SleepSpace9** [comment]
Could you please add again the "nogz" parameter for "/makeserver"?  It has been added by PeratX in former times because the building of phar aborted with an error on some Linux systems when compression was enabled. (e.g. my system).
Here's the old issue: https://github.com/iTXTech/Genisys/issues/671

**Comment by dktapps** [comment]
@SleepSpace9 it's now `no-gz`

**Comment by SleepSpace9** [comment]
ah okay, thank you!
