### ISSUE TITLE
getMovementSpeed() on null

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1604]
Build:Genisys 0ddc67f
PHP: 7.0.3
OS: Centos

$event->getPlayer()->getMovementSpeed();
error  getMovementSpeed(); on null.

Is there a way to check a player speed?

**Comment by XFuryMCPE** [comment]
Follow the template.

**Comment by ZedCee** [comment]
The recommended approach is to follow the template to help make sure your issue is easier and more concise to read, then replicate.  Then seeing your version I would recommend that you update typically.  Thank you @XFuryMCPE for recommending that.

Firstly I want to thank you for typing clearly, I can mostly read what your getting at @TDMidkwhatisxd.  However, you still have not followed the template and this seems an awful lot like a plugin related question.  So I recommend that you ask on gitter.im, Mattermost, or IRC.

Issue tickets are for problems with the vanilla functioning of a server.  Anything plugin related should be brought up with the developer of the plugin, or if you are working on some plugins yourself, you are welcome to ask in the chat rooms listed before.

**Comment by TDMidkwhatisxd** [comment]
Ok , im sorry!
