### ISSUE TITLE
How to delete /me from core

### ISSUE THREAD

**Issue by kkekof** [iTXTech/Genisys#1662]
#### Issue description
How to delete /me from core for add it from plugin

#### Steps to reproduce the issue
none

#### OS and versions

* Genisys: Kyrios
* PHP: 7.0.8
* Server OS: Ubuntu 16.04 LTS
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Driesboy** [comment]
https://github.com/Driesboy/Genisys/tree/patch-3

**Comment by ishitatsuyuki** [comment]
**No questions.** Next time you do that, beware of banning.

**Comment by Driesboy** [comment]
ok i remove it

**Comment by LordJoshie** [comment]
SO, TO NOT BE AN ASSHOLE, AND TO ANSWER THIS EASY FUCKING QUESTION...

Set the perm for your base group     -pocketmine.command.me  

THIS ISHITSUYAKI FUCK IS AN ASSHOLE.

**Comment by dktapps** [comment]
There's no need for that. We have little tolerance for people who don't read. It clearly states in the contribution guidelines to ask questions on Gitter, mattermost or IRC, instead of spamming our issue tracker. @LordJoshie I suggest you go and calm down. Behaviour like that will get you a ban if you're not careful.
