### ISSUE TITLE
Anvil bug

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1711]
Anvil can't enchant by enchant-book.
Item drop from anvil when set Name Tag by Anvil.

**Comment by ZedCee** [comment]
Anvils are currently limited, only allowing renaming.
It will require some extensive coding of the recipes to get them working to the vanilla standard, so this will take time.  A well-known limitation we will get to in a while.

Anvil naming functions as expected on the `master` branch, name-tags however are not yet implemented.  

You haven't provided any further information regarding the version you are using, so I am unable to assist any further.  If you are using a branch other than `master`, there will be errors and those branches are unsupported because they are in development (issue tickets are for the `master` branch).

**Comment by dktapps** [comment]
#888
You're getting irritating. Do read the contribution guidelines and FOLLOW THE TEMPLATE.

**Comment by ibookcc** [comment]
@ZedCee so sorry. my ignorance is causing you trouble and waste you time.):
