### ISSUE TITLE
TP + Bed :'D

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1744]
#### Issue description
TP + Bed

#### Steps to reproduce the issue
1. sleep bed
2. tp

#### OS and versions
* Genisys: https://github.com/iTXTech/Genisys/tree/3d8f4377f30907ca8b01c2de6fcb7a7a477941c6
* PHP: 7.0.10 (Genisys script)
* Server OS: Ubuntu 14.04.4 LTS
* Game version: 0.15.6 (Android)

#### Crashdump, backtrace, memory dumps, plugins list or other files
![14114084_837320386398495_436433307_o](https://cloud.githubusercontent.com/assets/8324198/17862710/b2c6999c-6896-11e6-8c57-ae8c96475dd5.jpg)

**Comment by ZedCee** [comment]
I can confirm that beds and teleportation behave a little hinky.
Upon teleportation, the player is still in a "sleep" state and continues until the night is through.  The player however can still leave the "sleep" state and gameplay does not seem considerably impacted.  
If this issue is not with the client, then I suspect it will not be a priority.

**Comment by dktapps** [comment]
This should be an easy fix. Let's see.

**Comment by dktapps** [comment]
I have PRed a fix. Please test at #1751.
