### ISSUE TITLE
Wtf dude NEED TO BE READ!!!

### ISSUE THREAD

**Issue by BudderSticks** [iTXTech/Genisys#1818]
Dude, I need serios help with this problem! If you dont want to be spammed, then unsubscribe to the thread... Dont be a idiot and be rude and shut down someones issue! My server is getting destroyed because of this problem! @dktapps

**Comment by dktapps** [comment]
Did _you_ not read? _Take this discussion somewhere else and stop spamming people's notifications._

**Comment by dktapps** [comment]
The key point being _take it somewhere else_. We have chat for this purpose. If you ever bothered to read the contribution guidelines you'd know this.

**Comment by BudderSticks** [comment]
Where else do I take this. You are a dev of tjis, you should help fix this...

**Comment by dktapps** [comment]
[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by BudderSticks** [comment]
Okay....... So you are saying for me to tale this to Git? I dont have git...or any of that stuff...

**Comment by SleepSpace9** [comment]
@BudderSticks I can understand dktapps, he's getting a notification for every single comment.
Because of this comments should not be used like chat - come to Mattermost or Gitter, but please let this be the last comment for now here!

https://mattermost.itxtech.org/itxtechnologies/channels/genisys
https://gitter.im/iTXTech/Genisys?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by GlitchPlayer** [comment]
What will be the purpose of chat? Go somewhere else. Devs are busy working on here but they receive spamming issues...

**Comment by BudderSticks** [comment]
I dont have those other programs. I am sorry...

**Comment by BudderSticks** [comment]
Ill try tho

**Comment by GlitchPlayer** [comment]
they are online dude

**Comment by gaoyichuan** [comment]
GOODBYE SPAMMER!
