### ISSUE TITLE
Stupid Genisys

### ISSUE THREAD

**Issue by karanpatel567** [iTXTech/Genisys#1824]
ClearSky was right u don't take things seriously u do shut down issues without speaking respectfully ato east they respectfully what I say u Genisys don't u just shut them down and say your banned I'm moving back to ClearSky! And if u didn't know they are taking codes from you guys
Come on BAN ME I don't care!

**Comment by GlitchPlayer** [comment]
They take code with permission. You dumb ass

**Comment by GlitchPlayer** [comment]
And also, one rule in here. Follow the contributions guidelines!!!! Are you reading???? Are you some sort of kid in here???

**Comment by GlitchPlayer** [comment]
Devs are busy with there lives, they are not focused on spammers!

Unlike you, you just contributing spam issues. DUMB ASS

**Comment by GlitchPlayer** [comment]
Clearsky takes some code from other server software. no offense. But Genisys have true code! They don't take codes. PR are completely fine since they are ppl work that wanted to add on genisys. Unlike you, you just eat, sleep, and repeat! The devs in here are working everyday!

**Comment by GlitchPlayer** [comment]
Why would you use 0.16 branch? 0.16 on mcpe are just yet on beta! 0.16 branch is on work. Have you read the 0.16 issue? It is not for a production use

**Comment by dktapps** [comment]
Go to ClearSky. You think we care if you do? We're open source, we don't get paid to do this. Idiots like you waste so much of our time we'll be glad to be rid of you.

Disclaimer: We are not in competition with ClearSky. We are two branches of the same project with different objectives.

**Comment by thebigsmileXD** [comment]
Its definitely enough now.
@karanpatel567 I am main dev on ClearSky (No offense @robske110 :wink:)
I created the stuff in the Readme. Guess what? I had a conversation with @ishitatsuyuki yesterday about what happened. It kind of turned out we just misunderstood each other due to language problems, missed some important parts in the sentences.
Genisys is a good, working Core (spoon). Same thing for Nukkit, ClearSky, (..okay, won't list IM, is not good anymore), MiNET etc, ignoring the forks and spoons of all these and ignoring some unknown like Steadfast2. Nice, working cores, all with several different features. ClearSky has Gamerules per world, several unique items and good Redstone and nice chunk loading performance. Genisys has a weird chunk loading performance, but alot more features! Working enchanting, cauldrons and implemented effects on fighting, also finally a fixed inventory. Also a good generator, just like Nukkit. Sure, nukkit has the best generator so far, but a lack of plugins (not core fault, just too less plugin coders), some performance options etc. (i am not that familiar with nukkit to say any more stuff).

Also your english grammar may also be a cause of missunderstanding. Next time try to talk nicer and maybe think first.

Everyone should use the core his heart desires. ClearSky and Genisys are finally communicating, making fixing bugs etc way faster, win-win for both sides!

And now to you, @GlitchPlayer .
They have the 0.16 branch, sure. Because they prepare their code for it, so they and other cores can be prepared when the REAL update is out. Me myself also tries to help: with new item id's, entity id's and more. (Remember, i am from ClearSky. Collaboration ftw.)

Stop insulting others, you don't know them in personal.

PS: Also, you spammed most..
![image](https://cloud.githubusercontent.com/assets/8733998/18168180/cefd1b02-7054-11e6-96e6-28a9f65779cf.png)

**Comment by thebigsmileXD** [comment]
FYI: 0.16: #1807 and the new Readme.md

**Comment by dktapps** [comment]
Well, I had referenced that issue once already... (^_^) :D

**Comment by thebigsmileXD** [comment]
Didn't show up here.

**Comment by dktapps** [comment]
On the first spammed one: #1819 
Then there was #1820 , and finally this

**Comment by GlitchPlayer** [comment]
haha @thebigsmileXD Ikr.
