### ISSUE TITLE
Genisys simply freezes 3 to 10 minutes

### ISSUE THREAD

**Issue by thebigsmileXD** [iTXTech/Genisys#1850]
I'd really like to provide more information, but i don't have any :c

**Comment by Leo3418** [comment]
Please consult #1788. Are you experiencing the same issue?

**Comment by thebigsmileXD** [comment]
I do not. I don't get crashes, i get hickups. Here are 2 dumpmemory things, i hope those can help.
[memoryDump_Sun_Sep_4-17.31.12-CEST_2016.zip](https://github.com/iTXTech/Genisys/files/454169/memoryDump_Sun_Sep_4-17.31.12-CEST_2016.zip)
[memoryDump_Sun_Sep_4-02.47.55-CEST_2016.zip](https://github.com/iTXTech/Genisys/files/454168/memoryDump_Sun_Sep_4-02.47.55-CEST_2016.zip)

**Comment by Striker209** [comment]
@dktapps I think this issue is a priority (as @FaanMaario's one) because this makes Genisys unstable. I also had this issue and since I enabled check-movement back again, I have no more freeze like the one described... Meanwhile, I get an infamous memory leak that crashes my server to a regular time interval... *I dunno if it comes from my core plugin or Genisys even if I checked my code for a long time*

**Comment by dktapps** [comment]
From my saved replies:

To help us resolve this, you can create a memory dump when your server is at high usage and upload it and send a link.

How to create a memory dump:
1. Open your `pocketmine.yml` and set `debug.commands` to `true`
2. Run your server. You can use `/status` to see how much memory your server is using.
3. When the memory usage is near the limit, run `/dumpmemory`. This will create a memory dump in your server folder under `/memory_dumps`.
4. Compress the memory dump and upload it to a file host and post a link so that our developers can examine it.

Thanks for your cooperation.

**Comment by dktapps** [comment]
Hmm. Reproduced, once. Not sure how. My server crashed less than a minute after starting with an out of memory error. Something is not right here

**Comment by MattWAnderson** [comment]
We have oddly ran into this also... for us deleting the genysis.yml file and rebooting corrected for us... not sure why.

**Comment by legoboy0215** [comment]
When the server freezes, check CPU usage with top. Is it abnormally high?

**Comment by thebigsmileXD** [comment]
Its not, same as usual.

**Comment by legoboy0215** [comment]
Whaat? I get abnormal CPU usages like suddenly, and server freezes until I kill -9 it. It does it randomly so I don't have a chance to dump memory.

**Comment by dktapps** [comment]
Can you still reproduce this after 049aded7c4abfab7f4bef666f93253fbaa3b9021 ?

**Comment by MajorPlayz** [comment]
Have had same issue however downloaded new genisys phar from the Jenkins CI server and all was fine... As others have said, definetley not a Memory issue. Have tried with 4GB ram which is plenty enough and still crashes. Latest phar does work however and you can download the phar im using [here](http://majorcraft.xyz/LatestPhar.phar) _Hosted on my googledrive_ **Note: It is a genisys phar and I am not advertising any other software because why... Genisys = life :D**

**Comment by thebigsmileXD** [comment]
@dktapps yes

**Comment by Muqsit** [comment]
I can no longer produce it
Anyone still having this problem?

**Comment by thebigsmileXD** [comment]
Sadly yea. I want to mention one thing: i use windows

**Comment by thebigsmileXD** [comment]
Oh update: have't had this with genisys for a while.
