### ISSUE TITLE
Genisys.yml: unknown changes

### ISSUE THREAD

**Issue by dterweij** [iTXTech/Genisys#1892]
#### Issue description

After each Genisys version change something like this is showed:

```
[22:57:10] [Server thread/NOTICE]: Your genisys.yml needs update
[22:57:10] [Server thread/NOTICE]: Current Version: 18   Latest Version: 19
```

But you never mention what is changed. To look up the changes in the commit mass is very difficult to find for a lot users.

**Suggestion:**
Provide a changelog for Genisys.yml with changes for each version.

**Like:**

```
Version 32:  Date: aug 4 2017
Removed: Section: yyyyy: $settingx ; because not needed anymore
Added: Section xxxx: $weather = <on | off> ; Control weather system

Version 31: Date: oct 12 2016
etc etc.  
```
#### Steps to reproduce the issue

Use older yml file.
#### OS and versions

- Genisys:  e19117fcea34dd68ba6f867b60a5592b77931978 (I build my own phars, this is the closest commit number that I use.)
- PHP: **7.0.11RC1** (Remi)
- Server OS: **CentOS 6** / 64Bit
- Game version: **0.15.7.2** (Android & Win 10)
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by dktapps** [comment]
I plan to remove genisys.yml in the future and implement a config auto updater that will merge config changes while retaining relevant previous configs. There's no need for 2 of them. All it does is cause confusion, especially since some configs are duplicated and others are scattered between the two files.
