### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1916]
Genisys: 82f9e7f
PhP: 7.0.1
Os: Windows

If you cancel OnDropItem , blocks wont drop but your item will be lost :( !
So , it breaks auth plugins :(  !

And there are duplicate items bug.
How i reproduced it?
Craft diamond armours , take from chest 2 sticks , diamonds droped on ground, i take it , and i got more diamonds!

But , fix that , for the auth plugin pls :(

**Comment by ishitatsuyuki** [comment]
**Format properly. Horrible.**

**Comment by Muqsit** [comment]
PHP 7.0.1? You know...PHP 7.1.0 beta builds have already released...you're way behind, mate. Get PHP 7.0.8+

Anyways, I can't reproduce ANY of those bugs. The plugins you're using might be poorly coded or it might be due to you using a very old version of PHP. Providing console errors (if any) might help.

**Comment by TDMidkwhatisxd** [comment]
Console give no errors!
I swiched to xbox auth now! :). !
