### ISSUE TITLE
Player entities staying on server after disconnecting

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1940]
#### Issue description

player's human entity will stay on the server sometimes after leaving/disconnecting

#### Steps to reproduce the issue

i dont know ..

#### OS and versions

* Genisys: 971b506
* PHP: 7.0.9
* Server OS: linux
* Game version: 0.15

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by XFuryMCPE** [comment]
k thanks

**Comment by dktapps** [comment]
...

**Comment by XFuryMCPE** [comment]
why reply when it gets closed. 😐 makes no sense

**Comment by dktapps** [comment]
Because you made a comment that makes no sense, and closed it yourself.

**Comment by XFuryMCPE** [comment]
Then tell me "your comment makes no sense, please revise it", rather than ignoring until I close it myself.

**Comment by dktapps** [comment]
Just because nobody replied to you within a couple of days doesn't mean we are ignoring the issue. It simply means we haven't got anything to say, and/or nobody has had time to investigate it yet.. If you close the issue, it is assumed to be resolved. Don't be so big-headed as to assume we are going to make you our priority, especially not after your behaviour on Twitter.

**Comment by XFuryMCPE** [comment]
😂 ok

**Comment by SOF3** [comment]
You have provided very little information on how to reproduce such issue, so it is very difficult to know whether this issue has been fixed. Even if it has been fixed, we don't know if it is the issue that you are mentioning, or anothe rone.
