### ISSUE TITLE
Minecarts floating when placed

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#2148]
#### Issue description

When minecarts are placed, they float above the ground and don't sit on the floor. No ride button when near minecart either. Since 0.16
#### Steps to reproduce the issue

Place a minecart
#### OS and versions

* Genisys: f7104d6a
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: 0.16.0.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
![screenshot_2016-11-04-23-17-07](https://cloud.githubusercontent.com/assets/17614796/20025355/7edeb8d8-a2e5-11e6-9a64-035c7c5e767f.jpg)

**Comment by CaveCrafterLP** [comment]
You can ride a MineCart, when you Tap the Minecart a few seconds long, but then you will sitt under the minecart. And it moves automatic without Boosterrails (Im not that good in Englisch because idont speak it verry often)

Please fix the "under the minecart bug" because i would like to build a Rollercoaster. Im not a hater: I LOVE GENISYS!

**Comment by iPocket** [comment]
#2180
