### ISSUE TITLE
Combat Glitch

### ISSUE THREAD

**Issue by MeddlingMari** [iTXTech/Genisys#2171]
If you're in combat with another player in a pvp zone you can go back to spawn with the command. It bypasses the CombatLogger plugin for some reason and I don't understand how it's happening. This is on Minecraft Pocket Edition btw.

**Comment by jojoe77777** [comment]
I believe the problem is PlayerCommandPreProcess event not fired (properly?) when using ./command

**Comment by starterdragon** [comment]
Didn't follow issue template?

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

Please don't waste our time just because you don't understand. Use our chat for community support instead.
