### ISSUE TITLE
Iron door can't be locked.

### ISSUE THREAD

**Issue by jerryzooyoyo** [iTXTech/Genisys#222]
In single player, iron doors need redstone to open them.
But in Genisys, iron doors can be opened by touching them.
I think this is a bug. Could you fix it? Thanks.

**Comment by gaoyichuan** [comment]
Confirm it, wait for somebody to fix.

**Comment by PeratX** [comment]
Iron doors can be activated in PocketMine preset.

**Comment by jerryzooyoyo** [comment]
How to do that?

**Comment by gaoyichuan** [comment]
@PeratX  We need to work on the redstone control of the iron door..

**Comment by jerryzooyoyo** [comment]
Redstone can be worked on iron doors.
I think you guys just copied from other kinds of doors, so that iron doors can be opened by touching, just the same with other doors.
Sorry, it's just guessing.

**Comment by gaoyichuan** [comment]
@

**Comment by gaoyichuan** [comment]
Mistakenly closed..
@jerryzooyoyo Yes, you are right.

**Comment by Awzaw** [comment]
This change breaks several plugin that count on standard pocketmine door operation. Also in some cases server owners may want both ways of opening iron doors, for example if the tap method is restricted by a plugin that locks iron doors. How about adding an option instead of just cutting stuff out that breaks compatibility?
