### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by DesPlaysMC** [iTXTech/Genisys#266]
every time about 20+ secs after the server has successfuly loaded, the console will stop running, as if the server was frozen and a message is displayed at the bottom of the console:
bin\php\php.exe: Exit 127
is this a misconfiguration or is there a problem with the php? help

**Comment by PocketKiller** [comment]
try again, also happened for me first launch.

**Comment by DesPlaysMC** [comment]
i kept on trying but it doesnt work. any solutions for this @PocketKiller

**Comment by Muqsit** [comment]
That happened to me too! It was probably because the system couldn't read/open bin\php\php.exe

You must execute these commands in console...
UBUNTU
`apt-get update`
`apt-get install make autoconf automake libtool m4 wgetgzip bzip2 bison g++`

CentOS
`yup update`
`yum install make autoconf automake libtool m4 wgetgzip bzip2 bison g++`
