### ISSUE TITLE
Raklib error

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#822]
#### Issue description

Some network issue..
#### Steps to reproduce the issue

Erm..turn on debug..not sure. I have issues with the server randomly deciding it wont let any players join, as if the port is not opened or my network sucks but i have 90mbs download and 10mbs upload. Nothing i do seems to fix it tried reseting pc and modem but it just decides when it wants to connect again. Could these errors be linked or is my network provider not happy with me running a game server? lol
#### OS and versions

* Genisys: 292
* PHP: 7
* OS: windows

#### Crashdump, backtrace or other files (not crash dump..but error)
```
[22:14:38] [RakLibServer thread/DEBUG]: An E_NOTICE error happened: "Uninitialized string offset: 33" in "/src/raklib/protocol/Packet" at line 42
[22:14:38] [RakLibServer thread/DEBUG]: #0 /src/raklib/protocol/Packet(73): raklib\protocol\Packet->getShort()
[22:14:38] [RakLibServer thread/DEBUG]: #1 /src/raklib/protocol/UNCONNECTED_PONG(43): raklib\protocol\Packet->getString()
[22:14:38] [RakLibServer thread/DEBUG]: #2 /src/raklib/server/Session(510): raklib\protocol\UNCONNECTED_PONG->decode()
[22:14:38] [RakLibServer thread/DEBUG]: #3 /src/raklib/server/SessionManager(174): raklib\server\Session->handlePacket(raklib\protocol\UNCONNECTED_PONG object)
```

**Comment by deotern** [comment]
//To Genisys Team => "Please close this issue, because it's not a bug at all"//

This is an UDP Flood Attack, the hardest attack to stop... You're in the hot soup...
Because my server is suffering from this attack and I get exactly the same error...

Solution: mitigate or stop the attack... (P/S: Reinstalling Pocketmine, restarting, etc won't fix it)

Wow, there're quite many servers suffering from this UDP Flood Attack... I'm wondering who is behind this

**Comment by ishitatsuyuki** [comment]
Hmm. This is showing an error, means something have to been fixed.

**Comment by deotern** [comment]
Nope!!
Trust me, the bug shown is because something is wrong in the Packets Sent to the server, which is UDP Flood Attack...

I'm currently suffering from this attack too... Genisys is running, but cannot connect to server, when i turn on debug, showing these errors... But, I confirmed it's an attack. It could be Dos or DDos or UDP or etc etc attacks. For me, it's UDP Flood Attack

**Comment by ishitatsuyuki** [comment]
At least we should have some ability to reject invalid packets. Do you think an HTTP server should log errors or even malfunction on malicious packets?

**Comment by deotern** [comment]
I think nope, because if you searched back, this issue exists about 1 to 2 years ago in official Pocketmine. If there's a way to filter the packet in Pocketmine, it should be added already in 2 years ago...

+ Based on my exp, blocking, filtering job is done before you reached Pocketmine. This is something like DDOS Attack, and if this is an attack, you should go and stop the attack instead of keep editing Packet Handler in Pocketmine .... 

P/S: Not every issue shows an error, means something have to be fixed.

**Comment by ishitatsuyuki** [comment]
Based on my experience, filtering can be either done by transport level or protocol level. PocketMine already has a little banning feature for malicious packets.

**Comment by deotern** [comment]
Yep, it's "a little"

But the fact is stopping the attack is better than editing the source code
If it can be 100% done in Pocketmine, then what is the usage of Firewall, DDOS Mitigation, Packet Limitation and all security programs installed on the server? Those Firewall programs are used to help you to resolve the security issue arise on the server, protect your server from series of attacks...

Additionally, even you can filter all the malicious packets. Your server traffic will still SUPER HEAVY.... causes every players lagging...

**Comment by ishitatsuyuki** [comment]
Don't forget that only ISP level block can open up the bandwidth.

AFAIK, there is nobody using professional DDoS resources just for attacking PE server. This is controllable by software.

**Comment by deotern** [comment]
Alright.... Whatever... then label this as a bug
Hope you guys can fix this :)

Im going to resolve my attacks now

**Comment by gaoyichuan** [comment]
@PeratX if you want to treat it as a question, then don't close it.

**Comment by XxDXM-hippiexX** [comment]
Is there anything i can do about this? and..is my personal data in danger or is it just to mess with the server?

**Comment by Lucario2** [comment]
LOL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by PeratX** [comment]
I think you are under attack.

**Comment by XxDXM-hippiexX** [comment]
Why is that funny? bc i dont know what a UDP attack is? lol but it sounds about spot on..sends a bunch of useless information causing it to use up all my bandwidth? but why dose it not slow anything else down? like its just the server.

**Comment by XxDXM-hippiexX** [comment]
Also what can i do to stop these? any recommended service i can look at?

**Comment by deotern** [comment]
@XxDXM-hippiexX 
1) Wait for the attacker to stop, (most likely not, because many servers attacked for more than 3 weeks...)
2) Google up "The way to stop UDP Flood"

**Comment by XxDXM-hippiexX** [comment]
3 weeks at once? o.0 mine usualy only last a few hours you a day..but thank you will do. If there is a way to do this within genisys or a plugin that would be sweet tho!

**Comment by deotern** [comment]
@XxDXM-hippiexX 
No, by 3 weeks, I mean the attack last for 3 weeks... never stopped... :(

Most likely, not, you should do this with your server firewall... ;)

**Comment by PeratX** [comment]
Set up your firewall and this question can be closed :)
