### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/Genisys#884]
The chat is buggy it makes a bracket automaticly and after the bracket the color is away

**Comment by ishitatsuyuki** [comment]
Provide more details. Follow the template.

**Comment by diamond-gold** [comment]
![screenshot_2016-04-28-22-00-33](https://cloud.githubusercontent.com/assets/10301312/14888468/157f1d3a-0d8d-11e6-9e58-7c18518bc511.png)
When you send chinese characters, it breaks up with space in between

**Comment by Muqsit** [comment]
That's a 0.14.2 *feature*

**Comment by Driesboy** [comment]
its not only with chinese

**Comment by SleepSpace9** [comment]
Yes, since 0.14.2 problem with special characters (like €). If a special character is in the line then there's an extra blank between every character. After a line break the text in the new line is displayed normally.
The conversion between different character sets seems to be affected by the new version and has to be adapted.

**Comment by JackboyPlay** [comment]
Thats so sh*t
